spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/campusgo
spring.datasource.username=postgres
spring.datasource.password=@Mph13nhd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false


